### ISSUE TITLE
Erase Flash Option w/ Custom zip or bin

### ISSUE THREAD

**Issue by medentem** [meshtastic/web-flasher#105]
It appears when flashing a custom zip or bin file, the erase flash option is not available. That would be super helpful to properly make use of the `userprefs` capability which requires a wiped device.

**Comment by thespillmonkey** [comment]
You need to use the firmware.factory.bin file from compile. And it needs to be named exactly that. 
And it will work :)

**Comment by jp-bennett** [comment]
Trying this with my tbeam, both on the official flasher and a locally hosted one, I'm getting "invalid header: 0xa8120c42" spammed in the log afterwords. Is this something weird with my builds?

**Comment by thebentern** [comment]
I'm assuming this needs to be the merged binary at 0x00.

**Comment by medentem** [comment]
This was fixed with https://github.com/meshtastic/web-flasher/pull/106
