### ISSUE TITLE
Update Alert Text when "Full Erase and Install" is checked

### ISSUE THREAD

**Issue by Xaositek** [meshtastic/web-flasher#122]
With the updates to the Security documentation, it seems logical to link the alert text to this page.

We'd want to link a portion of "Back up the device’s public and private keys before a full erase and install to restore them after re-flashing if needed." to the updates found here - direct link - https://meshtastic.org/docs/configuration/radio/security/#security-keys---backup-and-restore

**Comment by RCGV1** [comment]
Maybe the flasher could somehow check if the node is 2.5+ and if is a older version to not present the alert

**Comment by garthvh** [comment]
The whole purpose of the web flasher is to give people an option that does not need the cli.
