### ISSUE TITLE
Serial Log Gibberish if Upload Baud is not 115200

### ISSUE THREAD

**Issue by pdxlocations** [meshtastic/web-flasher#20]
After the install, the serial monitor is not set to correct baud to display incoming data.  Tested with TBeam and HeltecV3.

**Comment by thebentern** [comment]
I have no control over this sadly. The browser prevents me from re-opening webserial with a different baud rate without user interaction. It has to be trigger by a button or other user initiated means. Perhaps I could prevent the serial monitor from displaying anything if the baud rate is not 115200.
