### ISSUE TITLE
Project works on localhost but doesnt when deployed to vercel

### ISSUE THREAD

**Issue by its-aomi** [meshtastic/web-flasher#26]
Hi the project seems to work fine on localhost however on deployment to vercel it doesn't. Looks like due to the api that gets the firmware list as everything works fine except for the firmware list which doesn't show when deployed to vercel. 

How do i overcome this and load the firmware list?
![image](https://github.com/meshtastic/web-flasher/assets/103031412/4135c0e3-bfba-48d8-a306-8ef1f3268917)

**Comment by sachaw** [comment]
Yeah, that's the CORS policy we have, is there any reason you want to deploy this yourself?

**Comment by its-aomi** [comment]
Yeah, i am trying to deploy this to my own vercel account for testing purposes, tried on localhost worked fine, but tried online and didnt. Is there any way i can host the api myself?

**Comment by sachaw** [comment]
Yes, you can spin up an instance of the API.
It is located in the meshtastic/api repo.
