### ISSUE TITLE
Pico W detected as a Pico

### ISSUE THREAD

**Issue by clwgh** [meshtastic/web-flasher#68]
### Summary

Connecting a Pico W-based node to the web flasher and selecting the automatic selection, it incorrectly detects it as a Pico, not a Pico W, which I believe uses different firmware.

### Select the auto option, connection prompt
![s1](https://github.com/meshtastic/web-flasher/assets/115202757/652e059d-ba68-4f5c-92f5-2f20f79d8fcb)

### Pico erroneously detected
![s2](https://github.com/meshtastic/web-flasher/assets/115202757/e43f81d8-1209-4e28-96ed-e628ca1a1f74)

### Pico W is indeed available to select
![s3](https://github.com/meshtastic/web-flasher/assets/115202757/bba8b906-4acb-49f4-9d2c-a22b3361834e)

**Comment by thebentern** [comment]
The auto-detect returns whatever the hardware model protobuf the device has on it. It's an imperfect system because they are sometimes re-used between different hardware variants like the pico and a couple of the diy esp32 boards. Sadly I have no way of fixing this problem in the web flasher.

**Comment by clwgh** [comment]
I believe that the firmwares for the Pico and Pico W are different and not entirely compatible. Is that correct? If so, it would be worth preventing the auto detect from selecting either the Pico or Pico W and instead directing the individual to make the correct manual selection. This will prevent incompatible firmware from being applied.

**Comment by thebentern** [comment]
Indeed. I'm wondering if we can highlight the potential matched ones in the list

> Edit - to put it another way, restrict the auto-select to those models for which there is no such ambiguity. For all other models, the detection pops up a notice to the user asking them to make the correct selection manually.
