### ISSUE TITLE
[feature request] legacy support ttgo 1.0

### ISSUE THREAD

**Issue by Tom-Neverwinter** [meshtastic/web-flasher#69]
Flashing all modern builds dont work.

cant revert to an older version which is a major nuisence

app does not support older build of firmware. 

can we have the last working build and app version as it feels like a waste of money as these were cheap and did work just fine

**Comment by pdxlocations** [comment]
You may wish to [download a release](https://github.com/meshtastic/firmware/releases) and then [Flash with the CLI](https://meshtastic.org/docs/getting-started/flashing-firmware/esp32/cli-script/)
