### ISSUE TITLE
T-Echo 2.5 Position

### ISSUE THREAD

**Issue by nate2331** [meshtastic/web-flasher#90]
Im not sure if this is a known issue, but when I tested out 2.5 on my T-echo I could not get it to report a position at all. I tried a factory reset and reconfigured but no dice.

**Comment by caveman99** [comment]
when you say report a position, are you taliing about MQTT?

**Comment by nate2331** [comment]
It would not generate a dot on the map for node map, also it would not populate data in the environment field. Additionally the device metrics position log and node map were all greyed out. 

I have rolled back and now all those features are working fine
